const resData = [
  {
    id: 1,
    name: "Pizza Palace",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP8Mrijb_p4LUjQI2P7h4_ivFyYaW9owqmHw&s",
    rating: 4.5,
    cuisine: "Italian",
    deliveryTime: "30-40 min",
    price: 250,
    menu: [
      {
        id: 101,
        name: "Margherita Pizza",
        price: 220,
        description: "Classic cheese and tomato pizza",
        isVeg: true,
      },
      {
        id: 102,
        name: "Pepperoni Feast",
        price: 270,
        description: "Loaded with spicy pepperoni",
        isVeg: false,
      },
      {
        id: 103,
        name: "Garlic Bread",
        price: 120,
        description: "Crispy and buttery garlic bread",
        isVeg: true,
      },
    ],
  },
  {
    id: 2,
    name: "Burger House",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQta-X7n--roWdRnzHAJEewJ7zgah4p_EUdDg&s",
    rating: 4.2,
    cuisine: "American",
    deliveryTime: "20-30 min",
    price: 150,
    menu: [
      {
        id: 201,
        name: "Cheese Burger",
        price: 140,
        description: "Juicy beef patty with cheese",
        isVeg: false,
      },
      {
        id: 202,
        name: "Veggie Delight",
        price: 120,
        description: "Loaded with fresh veggies",
        isVeg: true,
      },
      {
        id: 203,
        name: "Fries",
        price: 80,
        description: "Crispy golden fries",
        isVeg: true,
      },
    ],
  },
  {
    id: 3,
    name: "Curry Express",
    image:
      "https://content.jdmagicbox.com/v2/comp/hyderabad/f4/040pxx40.xx40.200916204348.h2f4/catalogue/godavari-curry-express-chanda-nagar-hyderabad-restaurants-0kyziyozhv.jpg",
    rating: 4.8,
    cuisine: "Indian",
    deliveryTime: "35-45 min",
    price: 200,
    menu: [
      {
        id: 301,
        name: "Paneer Butter Masala",
        price: 180,
        description: "Rich and creamy paneer curry",
        isVeg: true,
      },
      {
        id: 302,
        name: "Chicken Curry",
        price: 220,
        description: "Spicy and flavorful chicken gravy",
        isVeg: false,
      },
      {
        id: 303,
        name: "Tandoori Roti",
        price: 30,
        description: "Clay oven baked bread",
        isVeg: true,
      },
    ],
  },
  {
    id: 4,
    name: "Sushi Central",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeqbS4w0jM2QmnT_gSBBNFsgUUsIONL4rcAg&s",
    rating: 4.6,
    cuisine: "Japanese",
    deliveryTime: "25-35 min",
    price: 450,
    menu: [
      {
        id: 401,
        name: "California Roll",
        price: 300,
        description: "Crab, avocado, and cucumber",
        isVeg: false,
      },
      {
        id: 402,
        name: "Veg Maki",
        price: 250,
        description: "Cucumber, carrot and rice roll",
        isVeg: true,
      },
      {
        id: 403,
        name: "Miso Soup",
        price: 120,
        description: "Traditional soy-based soup",
        isVeg: true,
      },
    ],
  },
  {
    id: 5,
    name: "Taco Town",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmeigWOw0NoVGa-nfodHcZ000iRexCI8xAsw&s",
    rating: 4.4,
    cuisine: "Mexican",
    deliveryTime: "20-25 min",
    price: 180,
    menu: [
      {
        id: 501,
        name: "Beef Taco",
        price: 150,
        description: "Spicy beef with lettuce and cheese",
        isVeg: false,
      },
      {
        id: 502,
        name: "Bean Taco",
        price: 130,
        description: "Black beans and avocado",
        isVeg: true,
      },
      {
        id: 503,
        name: "Nachos",
        price: 110,
        description: "With melted cheese and salsa",
        isVeg: true,
      },
    ],
  },
  {
    id: 6,
    name: "Vegan Delight",
    image:
      "https://images.moneycontrol.com/static-mcnews/2024/09/20240916115933_Rajasthani-vegetarian-cuisine-.jpg?impolicy=website&width=770&height=431",
    rating: 4.7,
    cuisine: "Vegan",
    deliveryTime: "30-35 min",
    price: 220,
    menu: [
      {
        id: 601,
        name: "Quinoa Bowl",
        price: 180,
        description: "Healthy quinoa with veggies",
        isVeg: true,
      },
      {
        id: 602,
        name: "Tofu Stir Fry",
        price: 200,
        description: "Tofu with bell peppers and soy sauce",
        isVeg: true,
      },
      {
        id: 603,
        name: "Vegan Wrap",
        price: 160,
        description: "Lettuce, hummus, veggies in wrap",
        isVeg: true,
      },
    ],
  },
  {
    id: 7,
    name: "Dragon Noodles",
    image:
      "https://b.zmtcdn.com/data/reviews_photos/82c/d03ebb4440f6322191b4c3ca0dfd582c_1706368014.jpg?fit=around|960:500&crop=960:500;*,*",
    rating: 4.3,
    cuisine: "Chinese",
    deliveryTime: "25-30 min",
    price: 210,
    menu: [
      {
        id: 701,
        name: "Hakka Noodles",
        price: 160,
        description: "Stir-fried noodles with veggies",
        isVeg: true,
      },
      {
        id: 702,
        name: "Chicken Manchurian",
        price: 190,
        description: "Spicy chicken in gravy",
        isVeg: false,
      },
      {
        id: 703,
        name: "Spring Rolls",
        price: 100,
        description: "Crispy veggie rolls",
        isVeg: true,
      },
    ],
  },
  {
    id: 8,
    name: "Biryani Hub",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-Ds3Ep6URB3bOHiUbl-2Mq4sI0idTpxM3Rg&s",
    rating: 4.9,
    cuisine: "Indian",
    deliveryTime: "30-40 min",
    price: 160,
    menu: [
      {
        id: 801,
        name: "Chicken Biryani",
        price: 180,
        description: "Fragrant rice with marinated chicken",
        isVeg: false,
      },
      {
        id: 802,
        name: "Veg Biryani",
        price: 150,
        description: "Biryani with seasonal vegetables",
        isVeg: true,
      },
      {
        id: 803,
        name: "Raita",
        price: 40,
        description: "Curd with onion and spices",
        isVeg: true,
      },
    ],
  },
  {
    id: 9,
    name: "Healthy Bites",
    image:
      "https://tb-static.uber.com/prod/image-proc/processed_images/653fb590ac8223854dd9b0aaef43774d/d24a30ada2fef6c54cef8739d94823b0.png",
    rating: 4.5,
    cuisine: "Salads & Bowls",
    deliveryTime: "15-25 min",
    price: 200,
    menu: [
      {
        id: 901,
        name: "Caesar Salad",
        price: 160,
        description: "Fresh lettuce with Caesar dressing",
        isVeg: true,
      },
      {
        id: 902,
        name: "Protein Bowl",
        price: 200,
        description: "Egg, quinoa, greens, and beans",
        isVeg: false,
      },
      {
        id: 903,
        name: "Fruit Bowl",
        price: 120,
        description: "Seasonal fruits mix",
        isVeg: true,
      },
    ],
  },
  {
    id: 10,
    name: "Grill Master",
    image:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/a0/a5/a9/chicken-box.jpg?w=900&h=500&s=1",
    rating: 4.6,
    cuisine: "Barbecue",
    deliveryTime: "40-50 min",
    price: 350,
    menu: [
      {
        id: 1001,
        name: "Grilled Chicken",
        price: 240,
        description: "Charcoal grilled chicken with spices",
        isVeg: false,
      },
      {
        id: 1002,
        name: "BBQ Paneer",
        price: 220,
        description: "Paneer cubes grilled in BBQ sauce",
        isVeg: true,
      },
      {
        id: 1003,
        name: "Corn on the Cob",
        price: 100,
        description: "Grilled sweet corn",
        isVeg: true,
      },
    ],
  },
];

export default resData;
